[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
elemental_vault = "Cq4qXN5syKaUt6if8wLH8fNZy2epnsByemJtpbis8awH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/justinlee/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
